version: '3'

services:
  rabbitmq:
    build: docker/rabbitmq
    container_name: rabbitmq_minotaur
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./app:/tools/app"
      - "./docker/input:/tools/input"
      - "./docker/output:/tools/output"

  amass:
    build: docker/amass
    container_name: amass_minotaur
    depends_on:
      - rabbitmq
    volumes:
      - "./app:/tools/app"
      - "./docker/input:/tools/input"
      - "./docker/output:/tools/output"

  assetfinder:
    build: docker/assetfinder
    container_name: assetfinder_minotaur
    depends_on:
      - rabbitmq
    volumes:
      - "./app:/tools/app"
      - "./docker/input:/tools/input"
      - "./docker/output:/tools/output"

  findomain:
    build: docker/findomain
    container_name: findomain_minotaur
    depends_on:
      - rabbitmq
    volumes:
      - "./app:/tools/app"
      - "./docker/input:/tools/input"
      - "./docker/output:/tools/output"

  subfinder:
    build: docker/subfinder
    container_name: subfinder_minotaur
    depends_on:
      - rabbitmq
    volumes:
      - "./app:/tools/app"
      - "./docker/input:/tools/input"
      - "./docker/output:/tools/output"

  massdns:
    build: docker/massdns
    container_name: massdns_minotaur
    depends_on:
      - rabbitmq
    volumes:
      - "./app:/tools/app"
      - "./docker/input:/tools/input"
      - "./docker/output:/tools/output"

#  resolvers:
#    build: docker/resolvers
#    container_name: resolvers_minotaur
#    depends_on:
#      - rabbitmq
#    volumes:
#      - "./app:/tools/app"
#      - "./docker/input:/tools/input"
#      - "./docker/output:/tools/output"

  httprobe:
    build: docker/httprobe
    container_name: httprobe_minotaur
    depends_on:
      - rabbitmq
    volumes:
      - "./app:/tools/app"
      - "./docker/input:/tools/input"
      - "./docker/output:/tools/output"

  dedup:
    build: docker/dedup
    container_name: dedup_minotaur
    depends_on:
      - rabbitmq
    volumes:
      - "./app:/tools/app"
      - "./docker/input:/tools/input"
      - "./docker/output:/tools/output"

  permutations:
    build: docker/permutations
    container_name: permutations_minotaur
    depends_on:
      - rabbitmq
    volumes:
      - "./app:/tools/app"
      - "./docker/input:/tools/input"
      - "./docker/output:/tools/output"
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8

